AWSTemplateFormatVersion: '2010-09-09'

Conditions:
  UseSingleSubnet: !Equals [!Ref SingleSubnetDeployment, 'true']

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, staging, prod]
  AccountId:
    Type: String
    Default: '427260910901'
  DomainName:
    Type: String
    Default: 'tonyffenochezra.com'
  VpcId:
    Type: String
    Default: 'vpc-03b72cde5edbd5472'
  PublicSubnet1Id:
    Type: String
    Description: ID of the first public subnet in the existing VPC
  PublicSubnet2Id:
    Type: String
    Description: ID of the second public subnet in the existing VPC
  PrivateSubnet1Id:
    Type: String
    Description: ID of the first private subnet in the existing VPC
  PrivateSubnet2Id:
    Type: String
    Description: ID of the second private subnet in the existing VPC
  SingleSubnetDeployment:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: Set to true to deploy with a single subnet (for testing only)

Resources:
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS tasks
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8090
          ToPort: 8090
          SourceSecurityGroupId: !Ref ALBSecurityGroup

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub 'products-api-${Environment}-alb'
      Scheme: internet-facing
      Type: application
      Subnets: !If 
        - UseSingleSubnet
        - [!Ref PublicSubnet1Id]
        - [!Ref PublicSubnet1Id, !Ref PublicSubnet2Id]
      SecurityGroups:
        - !Ref ALBSecurityGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub 'products-api-${Environment}-tg'
      Port: 8090
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /products

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub 'products-api-${Environment}'

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub 'products-api-${Environment}'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Ref TaskExecutionRole
      ContainerDefinitions:
        - Name: products-api
          Image: !Sub '${AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/products-api:latest'
          PortMappings:
            - ContainerPort: 8090
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  Service:
    Type: AWS::ECS::Service
    DependsOn: Listener
    Properties:
      ServiceName: !Sub 'products-api-${Environment}'
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref ECSSecurityGroup
          Subnets: !If 
            - UseSingleSubnet
            - [!Ref PrivateSubnet1Id]
            - [!Ref PrivateSubnet1Id, !Ref PrivateSubnet2Id]
      LoadBalancers:
        - ContainerName: products-api
          ContainerPort: 8090
          TargetGroupArn: !Ref TargetGroup

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/products-api-${Environment}'
      RetentionInDays: 7

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      Name: !Sub 'products-api.ecs.${Environment}.${DomainName}'
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApplicationLoadBalancer.DNSName
        HostedZoneId: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID

Outputs:
  LoadBalancerDNS:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
  ServiceURL:
    Value: !Sub 'http://products-api.ecs.${Environment}.${DomainName}/products'