# application-prod.yml
spring:
  datasource:
    url: jdbc:postgresql://product-api-prod.cluster-xyz.ap-southeast-2.rds.amazonaws.com:5432/productdb
    username: productapi
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: false

logging:
  level:
    com.tonyffenochezra.productapi: WARN
    org.springframework.security: ERROR