# application-dev.yml
spring:
  datasource:
    url: jdbc:postgresql://products-api-dev.cx0qnfjtc2ft.ap-southeast-2.rds.amazonaws.com:5432/postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    aws:
      secretsmanager:
        secret-name: rds!db-bbf53ad4-d50c-4c49-9de3-52e41933f93c
        region: ap-southeast-2
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


logging:
  level:
    com.tonyffenochezra.productapi: DEBUG
    org.springframework.security: DEBUG